# Generated by Django 3.1 on 2020-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_auto_20201002_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
