# Generated by Django 3.1 on 2020-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_auto_20201004_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField()),
                ('date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
