# Generated by Django 3.1 on 2020-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_carddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='email',
            field=models.CharField(default='spag18cs@cmrit.ac.in', max_length=20),
        ),
    ]
