# Generated by Django 3.1 on 2020-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_carddetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
